#==============================================================
#File generated by Vitis Model Composer(TM)
#Version: 2023.2
# 
#(c) Copyright 2017 - 2022 Xilinx, Inc. All rights reserved.
#(c) Copyright 2022 - 2023 Advanced Micro Devices, Inc. All rights reserved.
# 
#This file contains confidential and proprietary information
#of Xilinx, Inc. and is protected under U.S. and
#international copyright and other intellectual property
#laws.
# 
#DISCLAIMER
#This disclaimer is not a license and does not grant any
#rights to the materials distributed herewith. Except as
#otherwise provided in a valid license issued to you by
#Xilinx, and to the maximum extent permitted by applicable
#law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
#WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
#AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
#BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
#INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
#(2) Xilinx shall not be liable (whether in contract or tort,
#including negligence, or under any other theory of
#liability) for any loss or damage of any kind or nature
#related to, arising under or in connection with these
#materials, including for any direct, or any indirect,
#special, incidental, or consequential loss or damage
#(including loss of data, profits, goodwill, or any type of
#loss or damage suffered as a result of any action brought
#by a third party) even if such damage or loss was
#reasonably foreseeable or Xilinx had been advised of the
#possibility of the same.
# 
#CRITICAL APPLICATIONS
#Xilinx products are not designed or intended to be fail-
#safe, or for use in any application requiring fail-safe
#performance, such as life-support or safety devices or
#systems, Class III medical devices, nuclear facilities,
#applications related to the deployment of airbags, or any
#other applications that could lead to death, personal
#injury, or severe property or environmental damage
#(individually and collectively, "Critical
#Applications"). Customer assumes the sole risk and
#liability of any use of Xilinx products in Critical
#Applications, subject only to applicable laws and
#regulations governing limitations on product liability.
# 
#THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
#PART OF THIS FILE AT ALL TIMES.
#==============================================================
# This script sets up the environment to build the code using makefiles via terminal outside vitis model composer.
# This script needs to be sourced as shown below before running any make commands.
# > source setup.sh
# This script gets user into bash shell as shown below and sets up the environment.
# bash-4.2$ 
# Post that, go to any directory and trigger make as shown below:
# bash-4.2$make all
# At each directory make help will lists all the targets of that directory.
# bash-4.2$make help
# There are whole lot of targets that you can use.
# This script is in target directory. If user runs make all here, it will generate BOOT.BIN and 
# verifies its output against golden reference output.
# To go back to parent shell, run exit on terminal as shown below.
# bash-4.2$ exit

echo "Entered into bash shell."
echo "set up the environment."
echo "To go back to parent shell, run exit on terminal."

bash --rcfile .settings.sh


